# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 656e0926705fe7dd99834e258a4031789ac41c2ed963583c03f5966459dcc46ed6f2a3cc4c802a23e928467744e7bbf283cf3d45a86ebb642a7ed9f600b9d44b

test:
  secret_key_base: 34e86fa95ddb85d1f8a80a05d9530b4623e955140e9f922cffd12fdbfda71c71165930b5c2c9309c44c7ae31e87d962875feac330528559e4726e2ba2b659d9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
